
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION = 15;
  public static final int PUNTOYCOMA = 14;
  public static final int CADENA = 17;
  public static final int CONCATENACION = 10;
  public static final int DOSPUNTOS = 11;
  public static final int LETRA = 19;
  public static final int FLECHA = 5;
  public static final int COLOCHO = 9;
  public static final int ID = 16;
  public static final int POR = 13;
  public static final int SEPARADOR = 6;
  public static final int COMA = 8;
  public static final int LLAVEDER = 3;
  public static final int EOF = 0;
  public static final int DIGITO = 18;
  public static final int SIMBOLO = 20;
  public static final int CONJ = 4;
  public static final int DISYUNCION = 7;
  public static final int error = 1;
  public static final int LLAVEIZ = 2;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVEIZ",
  "LLAVEDER",
  "CONJ",
  "FLECHA",
  "SEPARADOR",
  "DISYUNCION",
  "COMA",
  "COLOCHO",
  "CONCATENACION",
  "DOSPUNTOS",
  "MAS",
  "POR",
  "PUNTOYCOMA",
  "INTERROGACION",
  "ID",
  "CADENA",
  "DIGITO",
  "LETRA",
  "SIMBOLO"
  };
}

